### ISSUE TITLE
yolov3模型定义方法与其他检测模型不同

### ISSUE THREAD

**Issue by hnuhchen** [YunYang1994/TensorFlow2.0-Examples#113]
各位好
关于模型库中的检测模型，我有一个问题想要咨询一下
为什么RPN，MTCNN，SSD等模型采用的是定义模型类的方法，而yolov3采用了函数API的方法呢？如下

1- With the “functional API”, where you start from Input, you chain layer calls to specify the model’s forward pass, and finally you create your model from inputs and outputs:

```
import tensorflow as tf
inputs = tf.keras.Input(shape=(3,))
outputs = tf.keras.layers.Dense(4, activation='relu')(inputs)
model = tf.keras.Model(inputs=inputs, outputs=outputs)
```

2- 第二种，类似于自己写一个subclass Model
in that case, you should define your layers in init and you should implement the model’s forward pass in call.
```
class MyModel(tf.keras.Model):
    def __init__(self):
        super(MyModel, self).__init__()
        self.dense1 = tf.keras.layers.Dense(4, activation=tf.nn.relu)
    def call(self, inputs):
        x = self.dense1(inputs)
        return x
model = MyModel()
```

感谢

**Comment by YunYang1994** [comment]
当时主要出于和 TensorFlow 1.x 版本兼容的考虑.

**Comment by hnuhchen** [comment]
@YunYang1994 好的，感谢
