### ISSUE TITLE
test.py nan

### ISSUE THREAD

**Issue by huhuhuhuha** [YunYang1994/TensorFlow2.0-Examples#121]
model.predict(),
第一张图片正常预测，从第二张图片开始都是nan,
VOC数据集和yymnist都是这样。

**Comment by mastergao57** [comment]
我也是这个情况。我是在跑video_demo的时候，视频只有第一帧预测正确，有预测框，后面都是nan，没有预测框。我怀疑是utils.load_weights(model, "./yolov3.weights")这一句的问题，于是把这一句放到了while true里，如代码所示，结果每一帧都有预测框了，但视频速度非常慢了，因为每次都要重新加载一次权重。我不知道是不是每当执行一次model.predict_on_batch(image_data)后，model就丧失权重了，就要重新加载权重才能再次预测。我的tensorflow==2.7.0。image_demo运行没问题。

**Comment by mastergao57** [comment]
您解决了吗？
