### ISSUE TITLE
raise TypeError("Using a `tf.Tensor` as a Python `bool` 

### ISSUE THREAD

**Issue by Pidem** [YunYang1994/TensorFlow2.0-Examples#23]
If anyone faces the following error message: 
TypeError("Using a `tf.Tensor` as a Python `bool` ) 

because of the BatchNormalization() function, just replace that function call with the built-in keras layer. 

bn: conv = tf.keras.layers.BatchNormalization()(conv)

**Comment by AnaRhisT94** [comment]
@Pidem  Thanks. This solved the first problem
Any ideas why I'm getting this error afterwards:
```
Traceback (most recent call last):
  File "image_demo.py", line 40, in <module>
    utils.load_weights(model, "./yolov3.weights")
  File "/yolov3-tf2-master/YunYang1994_TF2_YoloV3/TensorFlow2.0-Examples/4-Object_Detection/YOLOV3/core/utils.py", line 60, in load_weights
    assert len(wf.read()) == 0, 'failed to read all data'
AssertionError: failed to read all data
```
I understand that it failed to read the `yolov3.weights` file. But why this happens now?
