### ISSUE TITLE
TensorRT

### ISSUE THREAD

**Issue by Pidem** [YunYang1994/TensorFlow2.0-Examples#4]
Did anyone try to create the inference with TensorRT & TF2 for YOLOv3 by any chance, I cant get the trt.TrtGraphConverter() to convert for whatever reason....

**Comment by Pidem** [comment]
params = trt.DEFAULT_TRT_CONVERSION_PARAMS._replace(
        precision_mode='FP16',
        is_dynamic_op=True)

    converter = trt.TrtGraphConverterV2(
        input_saved_model_dir=saved_model_dir,
        conversion_params=params)
    converter.convert()
    logging.info("TRT model converted (1/2)")

    saved_model_dir_trt = "./tmp/yolov3_test.trt"
    converter.save(saved_model_dir_trt)

did the trick

**Comment by AnaRhisT94** [comment]
@Pidem 
I did this too, but how do you run the inference on the `saved_model_dir_trt`?

**Comment by momei123** [comment]
how do you run the inference on the saved_model_dir_trt?

**Comment by momei123** [comment]
.ckpt format cannot to trt.
