### ISSUE TITLE
tensorflow 2.0 - yolov3 - 如何制作自己的训练集进行训练

### ISSUE THREAD

**Issue by Zhangxiaof001** [YunYang1994/TensorFlow2.0-Examples#43]
我想做一个水果蔬菜之类的目标检测，请问按照您的数据格式，如何制作自己的数据集呢？我需要用lablImg标注成xml的标签，然后再转换成您的这个格式吗？有什么更加方便的方法吗

**Comment by shaojiestar** [comment]
我想做一个无人机的目标检测，不知道如何做数据集，兄弟如果有经验可以分享一下嘛

**Comment by Zhangxiaof001** [comment]
@shaojiestar 先标注，然后转换成txt格式。
