### ISSUE TITLE
请问保存的模型文件是.data文件，那如何保存为h5文件呢？

### ISSUE THREAD

**Issue by chajnoven** [YunYang1994/TensorFlow2.0-Examples#48]
强行保存为model.save('yolo3.h5')
会报错

**Comment by YunYang1994** [comment]
> 强行保存为model.save('yolo3.h5')
> 会报错

save_weights('yolo3.h5')

**Comment by chajnoven** [comment]
> > 强行保存为model.save('yolo3.h5')
> > 会报错
> 
> save_weights('yolo3.h5')

好的，感谢，已解决
