### ISSUE TITLE
有关YOLOv3中Dataset类确定真值在哪个prior中的疑问。

### ISSUE THREAD

**Issue by tsycnh** [YunYang1994/TensorFlow2.0-Examples#62]
在Dataset类中，函数preprocess_true_boxes中需要计算iou来判定将目标放在哪一个prior中。其中有一个判定条件是`iou_mask = iou_scale > 0.3`。似乎只要是iou大于0.3的prior都会被赋值。这样可能会出现只有一个目标，但却被赋值到多个prior的情况，请问为何要这样设计？有什么好处呢？

[dataset.py](
https://github.com/YunYang1994/TensorFlow2.0-Examples/blob/master/4-Object_Detection/YOLOV3/core/dataset.py)

**Comment by YunYang1994** [comment]
希望能解决你的困惑，https://yunyang1994.github.io/YOLOv3-03/

**Comment by tsycnh** [comment]
感谢，写的非常棒！

**Comment by pp1bb** [comment]
> https://yunyang1994.github.io/YOLOv3-03/

作者你好我也有相同的问题 但是这个链接打不开了
