### ISSUE TITLE
How to save model to file pb extension in yolov3 example?

### ISSUE THREAD

**Issue by huanbd** [YunYang1994/TensorFlow2.0-Examples#71]
Hi, Can you help, how to save model to **file pb extension**
I add this code `model.save('/saved_model/yolov3_mnist')` after loop training epoch, but the **pb file** is not complete. I use Netron to view graph of that file, but It is not true graph when compared to other **pb file**

**Comment by huanbd** [comment]
Hi, I've found the way to save model to a file **pb extension**
I've followed the guide of **Lei Mao**, you should read detail on [this link](https://leimao.github.io/blog/Save-Load-Inference-From-TF2-Frozen-Graph/)
I've added this code below loop training epoch
```
# Convert Keras model to ConcreteFunction
full_model = tf.function(lambda x: model(x))
full_model = full_model.get_concrete_function(
    tf.TensorSpec(model.inputs[0].shape, model.inputs[0].dtype))

# Get frozen ConcreteFunction
frozen_func = convert_variables_to_constants_v2(full_model)
frozen_func.graph.as_graph_def()

layers = [op.name for op in frozen_func.graph.get_operations()]
print("-" * 50)
print("Frozen model layers: ")
for layer in layers:
    print(layer)

print("-" * 50)
print("Frozen model inputs: ")
print(frozen_func.inputs)
print("Frozen model outputs: ")
print(frozen_func.outputs)

# Save frozen graph from frozen ConcreteFunction to hard drive
tf.io.write_graph(graph_or_graph_def=frozen_func.graph,
                      logdir="./frozen_models",
                      name="frozen_graph.pb",
                      as_text=False)
```

**Comment by motoleisure** [comment]
NameError: name 'convert_variables_to_constants_v2' is not defined
@huanbd I use the tf2.3 and occur this problem, can you tell me what is goning on ? THANKS !!!

**Comment by huanbd** [comment]
Hi @motoleisure , you can try this links to find problem, cause I've not used tf2.3 yet
 [https://github.com/tensorflow/tensorflow/issues/36391](https://github.com/tensorflow/tensorflow/issues/36391) 
[https://medium.com/@xianbao.qian/how-to-export-the-inference-model-in-tf2-279ac233915c](https://medium.com/@xianbao.qian/how-to-export-the-inference-model-in-tf2-279ac233915c)

**Comment by rmarru** [comment]
> NameError: name 'convert_variables_to_constants_v2' is not defined
> @huanbd I use the tf2.3 and occur this problem, can you tell me what is goning on ? THANKS !!!

I guess you are lacking an import:

```
from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2
```
